# Generated by Django 2.0.13 on 2019-05-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserApp', '0002_auto_20190522_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParserResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=300, verbose_name='Название')),
                ('article', models.CharField(max_length=200, verbose_name='Артикуль')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.CharField(max_length=200, verbose_name='Цена')),
                ('link', models.CharField(max_length=200, verbose_name='Ссылка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
        ),
    ]
