# Generated by Django 2.0.13 on 2019-05-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserApp', '0004_auto_20190524_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='class_value_products',
            field=models.CharField(default='', max_length=200, verbose_name='Класс продукта - значение'),
        ),
    ]
