# Generated by Django 2.0.13 on 2019-05-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserApp', '0009_parserresult_id_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_product', models.CharField(max_length=200, verbose_name='ID Товара')),
                ('changed_field', models.CharField(max_length=200, verbose_name='Поле изменения')),
                ('old_value', models.CharField(max_length=200, verbose_name='Старая информация')),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_product', models.CharField(max_length=200, verbose_name='Артикуль')),
            ],
        ),
    ]
