# Generated by Django 2.0.13 on 2019-05-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserApp', '0010_changesite_temporarytable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changesite',
            name='old_value',
            field=models.TextField(verbose_name='Старая информация'),
        ),
    ]
