# Generated by Django 2.0.13 on 2019-05-29 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parserApp', '0013_auto_20190529_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changesite',
            name='id_changed_site',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='parserApp.Site', verbose_name='Сайт'),
        ),
    ]
