# Generated by Django 2.0.13 on 2019-05-29 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parserApp', '0014_auto_20190529_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changesite',
            name='id_changed_site',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='parserApp.Site', verbose_name='Сайт'),
        ),
    ]
