# Generated by Django 2.0.13 on 2019-06-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserApp', '0015_auto_20190529_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='changesite',
            name='article_change_product',
            field=models.CharField(default='', max_length=200, verbose_name='Артикуль'),
        ),
        migrations.AddField(
            model_name='changesite',
            name='new_value',
            field=models.TextField(default='', verbose_name='Новая информация'),
        ),
    ]
