# Generated by Django 2.0.13 on 2019-07-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserApp', '0016_auto_20190618_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='atr_main_category',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Атрибут главной категории'),
        ),
        migrations.AddField(
            model_name='site',
            name='class_main_category',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Класс главной категории'),
        ),
        migrations.AddField(
            model_name='site',
            name='class_value_main_category',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Класс главной категории - значение'),
        ),
        migrations.AlterField(
            model_name='changesite',
            name='article_change_product',
            field=models.CharField(default='', max_length=200, verbose_name='Артикуль изменения'),
        ),
        migrations.AlterField(
            model_name='temporarytable',
            name='article_product',
            field=models.CharField(max_length=200, verbose_name='Артикуль временный'),
        ),
    ]
